spring.application.name=Magnus

spring.datasource.url=<db_url>
spring.datasource.username=<db_user>
spring.datasource.password=<db_passwd>

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.storage.path=<path_for_storage>
app.secret-key=<secret_key_for_HMAC>